apiVersion: v1
kind: Namespace
metadata:
  name: kundrio
  labels:
    # Pod Security Standard „restricted“ erzwingen
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
