# Gemeinsame rclone-Konfiguration aus Umgebungsvariablen (Remote "bk"), keine Konfigurationsdatei nötig.
: "${S3_ENDPOINT:?}" "${S3_BUCKET:?}" "${S3_ACCESS_KEY:?}" "${S3_SECRET_KEY:?}"
export RCLONE_CONFIG_BK_TYPE=s3 RCLONE_CONFIG_BK_PROVIDER=Other RCLONE_CONFIG_BK_ENDPOINT="$S3_ENDPOINT" \
  RCLONE_CONFIG_BK_ACCESS_KEY_ID="$S3_ACCESS_KEY" RCLONE_CONFIG_BK_SECRET_ACCESS_KEY="$S3_SECRET_KEY" \
  RCLONE_CONFIG_BK_REGION="${S3_REGION:-eu01}" RCLONE_CONFIG_BK_FORCE_PATH_STYLE=true RCLONE_CONFIG_BK_NO_CHECK_BUCKET=true RCLONE_CONFIG=/dev/null
