// Welche Tabelle steckt in welcher Datei des Sub-Account-Exports (src/lib/export.ts) – und welche bewusst nicht?
// Ein Test (export-coverage.test.ts) prüft gegen das Prisma-Schema, dass JEDES Modell hier entschieden ist.
// Neue Tabelle → hier eintragen UND in buildWorkspaceExport() exportieren (Art. 20 DSGVO, ADR-011 „kein Lock-in“).

export const EXPORTED: Record<string, string> = {
  Workspace: "workspace.json",
  Membership: "members.json",
  User: "members.json", // nur Name + E-Mail der Mitglieder
  Role: "roles.json",
  Team: "teams.json",
  TeamMember: "teams.json",
  Invitation: "invitations.json",
  Contact: "contacts.json",
  Activity: "activities.json",
  Company: "companies.json",
  LifecycleStage: "lifecycle-stages.json",
  PropertyDefinition: "properties.json",
  ContactList: "lists.json",
  ContactListMember: "lists.json",
  Pipeline: "pipelines.json",
  Stage: "pipelines.json",
  Deal: "deals.json",
  Ticket: "tickets.json",
  Task: "tasks.json",
  Event: "events.json",
  MeetingType: "meeting-types.json",
  Form: "forms.json",
  FormSubmission: "forms.json",
  Campaign: "campaigns.json",
  CampaignRecipient: "campaigns.json",
  EmailMessage: "emails.json",
  EmailEvent: "email-events.json",
  EmailTemplate: "email-templates.json",
  Suppression: "suppressions.json",
  Webhook: "webhooks.json",
  ApiKey: "api-keys.json",
  Inbox: "inboxes.json",
  Conversation: "conversations.json",
  Message: "conversations.json",
  KnowledgeSource: "knowledge-sources.json",
  WikiPage: "wiki.json",
  WikiRevision: "wiki.json",
  ChannelAccount: "channels.json",
  ChannelMetric: "channels.json",
  ChannelPost: "channels.json",
  LandingPage: "landing-pages.json",
  AnalyticsEvent: "analytics-events.json",
  Automation: "automations.json",
  AutomationRun: "automations.json",
  Process: "processes.json",
  ProcessVersion: "processes.json",
  ProcessRun: "process-runs.json",
  ProcessStepLog: "process-runs.json",
  CrmEvent: "crm-events.json",
  Approval: "approvals.json",
  AuditLog: "audit-log.json",
  ComplianceItem: "compliance.json",
  AiUsageLog: "ai-usage.json",
  EnrichmentSuggestion: "enrichment-suggestions.json",
  Mention: "mentions.json",
  Domain: "domains.json",
  Invoice: "invoices.json",
  Product: "products.json",
  Subscription: "subscriptions.json",
  SepaMandate: "sepa-mandates.json",
  DirectDebitBatch: "direct-debits.json",
  DirectDebitItem: "direct-debits.json",
  PaymentProvider: "payment-providers.json",
  Payment: "payments.json",
  BankAccount: "bank-accounts.json",
  BankTransaction: "bank-transactions.json",
  UsageSnapshot: "usage.json",
  StoredFile: "files.json",
};

/** Bewusst nicht im Sub-Account-Export – mit Begründung (erscheint im README des Exports). */
export const NOT_EXPORTED: Record<string, string> = {
  Agency: "Agentur-Ebene, nicht Teil eines Sub-Accounts",
  Session: "Anmeldesitzungen (Sicherheitsdaten)",
  RateLimitBucket: "technische Zähler, laufen ab",
  AnalyticsSalt: "geheimes Tagessalz für Besucher-Hashes (würde die Anonymisierung aufheben)",
  Job: "technische Warteschlange; Inhalte stehen in den fachlichen Tabellen",
  AppSetting: "Agentur-Einstellungen (Kostensätze, interne Versionen)",
  OAuthClient: "Zugänge externer Programme (Sicherheitsdaten)",
  OAuthCode: "Zugänge externer Programme (Sicherheitsdaten)",
  OAuthToken: "Zugänge externer Programme (Sicherheitsdaten)",
  CalendarConnection: "persönliche Kalender-Zugänge der Benutzer (Sicherheitsdaten)",
  KnowledgeChunk: "Vektor-Embeddings – lassen sich aus knowledge-sources.json neu berechnen",
};
